FROM reasonnative/web:4.10.0 as builder

RUN mkdir /app
WORKDIR /app

COPY package.json esy.lock dune-project morph_oidc_client.opam /app

RUN esy

COPY ./executable /app/executable
COPY ./library /app/library
COPY ./oidc /app/oidc

CMD ["esy", "x", "MorphOidcClient.exe"]
