name: "Test in nix"
on:
  pull_request:
  push:
    branches:
      - main
      - master
jobs:
  nix:
    name: "nix on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v30

      - name: "Run nix flake check"
        run: nix flake check --accept-flake-config

      - name: "Unit tests"
        run: nix develop --accept-flake-config -c dune runtest --instrument-with bisect_ppx --force --no-buffer

      - name: Send coverage report
        run: nix develop --accept-flake-config -c bisect-ppx-report send-to Codecov
        if: ${{ matrix.os == 'ubuntu-latest' }}
        continue-on-error: true

      - name: "Generate documentation"
        run: nix develop --accept-flake-config -c dune build @doc --force --no-buffer
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && matrix.os == 'ubuntu-latest' }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' && matrix.os == 'ubuntu-latest' }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: _build/default/_doc/_html
